### ISSUE TITLE
Server/Client connection not working on the cloud

### ISSUE THREAD

**Issue by ZiedChekir** [notgoodusename/tcp-udp-networking-basic#2]
Hi, I found a weird issue where the game server and client work locally but when I hosted the server on google cloud VM. I found a weird error : 

**this is the cloud version Logs**
    **SERVER**
```Initialized packets.

Server started on port 26950.

Incoming connection from 197.15.115.33:51451...

```

**CLIENT**

```
Initialized packets.
Message from server: Welcome to the server!
```

So the server receives the welcome packet but then it is unable to communicate further to spawn the player etc.
and to see the difference: 

**this is the Local version**
**SERVER**
```
Starting server...
Initialized packets.
Server started on port 26950.
Incoming connection from 127.0.0.1:51494...
127.0.0.1:51494 connected successfully and is now player 1.
```

**CLIENT**

```
Initialized packets.
Message from server: Welcome to the server! 
```

I disabled my firewall but it is still not working.
Do you have any idea how to fix this?

**Comment by notgoodusename** [comment]
I have no real idea about how to fix this, i will probably lock this repo since its pretty outdated, im sorry

**Comment by ZiedChekir** [comment]
Somehow disabling the console fixed the problem. Maybe it s outdated but it is well implemented and a good start for multiplayer game begginers so is it possible we chat further about the system on discord ?

**Comment by notgoodusename** [comment]
> Somehow disabling the console fixed the problem. Maybe it s outdated but it is well implemented and a good start for multiplayer game begginers so is it possible we chat further about the system on discord ?

sure
seka#5706
